name: Game Request
description: Request a new game
labels: [game request]
body:
  - type: markdown
    attributes:
      value: Please join our discord server to submit a Game Request, only use this as a backup!
  - type: markdown
    attributes:
      value: "[![Join us on Discord](https://invidget.switchblade.xyz/J3VPy5Vy8x?theme=light)](https://discord.gg/J3VPy5Vy8x)"
  - type: dropdown
    id: type
    attributes:
      label: Game Type
      multiple: false
      options:
        - Website
        - HTML file (downloaded)
      validations:
        required: true
  - type: markdown
    attributes:
      value: Please keep the file size low for HTML files, as there is a size limit on some hosting providers
  - type: input
    id: url
    attributes:
      label: The URL to the game?
      placeholder: If it is a HTML file, please type in 'Leave a comment' where it can be found
    validations:
      required: false
  - type: textarea
    id: comment
    attributes:
      label: Comment
      placeholder: Leave a comment
    validations:
      required: false
